# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    d360.apikey: '%env(D360_API_KEY)%'
    d360.phoneNumber: '%env(D360_DEFAULT_PHONE_NUMBER)%'
    d360.template: '%env(D360_TEMPLATE)%'
    d360.namespace: '%env(D360_NAMESPACE)%'
    d360.language: '%env(D360_LANGUAGE)%'
    d360.headerImage: '%env(D360_HEADER_IMAGE)%'
    d360.defaultSend: '%env(D360_DEFAULT_SEND)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
